[package]
name = "swc_nativewind"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
swc_core = { version = "0.86.*", features = ["ecma_plugin_transform", "ecma_parser" ] }

[dev-dependencies]
swc_ecma_transforms_testing = "0.137.44"
testing = "0.35.11"
