name: default-workflows

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup wasm32-wasi
      run: rustup target add wasm32-wasi

    - name: Lint
      run: cargo fmt --all --check

    - name: Run tests
      run: cargo test --workspace --verbose -- --include-ignored
